# Generated by Django 4.0.3 on 2022-07-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
