# Generated by Django 4.0.3 on 2022-08-06 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_order_details_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 6), null=True),
        ),
    ]
