# Generated by Django 4.0.3 on 2022-08-06 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2022, 8, 6)),
        ),
    ]
