# Generated by Django 4.0.3 on 2022-08-06 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
