# Generated by Django 4.0.3 on 2022-08-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
