# Generated by Django 4.0.3 on 2022-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery')], default='Ordered', max_length=20, null=True),
        ),
    ]
